import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
} from "recharts";

const CategorySales =  ({status,setStatus,categorySales,loadingCategory}) =>{

    return (
        <div className="bg-white rounded-xl border border-indigo-200 shadow-lg p-5 sm:p-6 mb-8 hover:shadow-xl transition-shadow duration-300">

            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
                <div>
                    <h2 className="text-2xl font-bold text-indigo-900">
                        Category Sales
                    </h2>
                    <p className="text-sm text-indigo-600 mt-1 font-medium">
                        Revenue generated by each category
                    </p>
                </div>

                {/* Status */}
                <select
                    value={status}
                    onChange={(e) => setStatus(e.target.value)}
                    className="border-2 border-indigo-300 rounded-lg px-4 py-2 bg-white text-indigo-900 font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500 hover:border-indigo-500 transition-colors"
                >
                    <option value="DELIVERED">
                        Delivered
                    </option>

                    <option value="SHIPPED">
                        Shipped
                    </option>
                    
                    <option value="PROCESSING">
                        Processing
                    </option>

                    <option value="CANCELLED">
                        Cancelled
                    </option>
                </select>
            </div>


            {/* Chart */}
            {loadingCategory ? (

                <div className="h-87.5 flex items-center justify-center text-gray-500">
                    Loading category sales...
                </div>

            ) : categorySales.length === 0 ? (

                <div className="h-87.5 flex items-center justify-center text-gray-500">
                    No category sales available.
                </div>

            ) : (
                <div className="w-full h-87.5">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart
                            data={categorySales}
                            margin={{
                                top: 10,
                                right: 20,
                                left: 10,
                                bottom: 10,
                            }}
                        >
                            <CartesianGrid
                                strokeDasharray="3 3"
                                vertical={false}
                            />
                            <XAxis
                                dataKey="category"
                                tick={{ fontSize: 12 }}
                            />
                            <YAxis
                                tick={{ fontSize: 12 }}
                            />
                            <Tooltip
                                formatter={(value) =>
                                    `₹${Number(value).toLocaleString("en-IN")}`
                                }
                            />
                            <Bar
                                dataKey="totalRevenue"
                                name="Revenue"
                                radius={[6, 6, 0, 0]}
                                fill="#6366f1"
                            />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            )}

            {/* Category Table */}
            {!loadingCategory && categorySales.length > 0 && (
                <div className="overflow-x-auto mt-8">
                    <table className="w-full text-left">
                        <thead>
                            <tr className="border-b-2 border-indigo-300 bg-indigo-50 text-sm">
                                <th className="pb-4 font-bold text-indigo-900 px-4">
                                    Category
                                </th>
                                <th className="pb-4 font-bold text-indigo-900 text-right px-4">
                                    Revenue
                                </th>
                                <th className="pb-4 font-bold text-indigo-900 text-right px-4">
                                    Orders
                                </th>
                                <th className="pb-4 font-bold text-indigo-900 text-right px-4">
                                    Items Sold
                                </th>
                            </tr>
                        </thead>

                        <tbody>
                            {categorySales.map((item, index) => (
                                <tr
                                    key={index}
                                    className="border-b last:border-b-0 border-indigo-100 hover:bg-indigo-50 transition"
                                >
                                    <td className="py-4 font-semibold text-indigo-900 px-4">
                                        {item.category}
                                    </td>
                                    <td className="py-4 text-right font-bold text-emerald-600 px-4">
                                        ₹{Number(item.totalRevenue).toLocaleString("en-IN")}
                                    </td>
                                    <td className="py-4 text-right text-indigo-700 font-medium px-4">
                                        {item.orderCount}
                                    </td>
                                    <td className="py-4 text-right text-indigo-700 font-medium px-4">
                                        {item.itemsSold}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}

export default CategorySales;